name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: SSH into server
		uses: appleboy/ssh-action@master
		with:
		  host: 65.0.89.198
		  username: ubuntu
		  key: ${{ secrets.SSH_PRIVATE_KEY }}
		  script: |
			'cd /home/ubuntu/django-notes-app && git pull'
