name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh ubuntu@65.0.89.198 'cd /home/ubuntu && git pull'
          # Replace "user" with your server's username and "your-server-ip" with the actual IP address
